github.com:
    users:
        Hwks-9026:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: Hwks-9026
